/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v1/combustiveis": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Combustiveis */
        get: operations["get_combustiveis_api_v1_combustiveis_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/ref_compra": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Listar Ref Compra */
        get: operations["listar_ref_compra_api_v1_ref_compra_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/ref_venda": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Listar Ref Venda */
        get: operations["listar_ref_venda_api_v1_ref_venda_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/operacoes": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Criar Operacao Endpoint */
        post: operations["criar_operacao_endpoint_api_v1_operacoes_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/balanco": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Obter Balanco */
        get: operations["obter_balanco_api_v1_balanco_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** BalancoConsultaResponse */
        BalancoConsultaResponse: {
            /** Ano */
            ano: number;
            /** Total Compra */
            total_compra: number;
            /** Total Venda */
            total_venda: number;
            /** Diferenca */
            diferenca: number;
        };
        /** CombustivelSchema */
        CombustivelSchema: {
            /** Id */
            id: number;
            /** Nome */
            nome: string;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** OperacaoCreate */
        OperacaoCreate: {
            /**
             * Combustivel Id
             * @description ID do combustível
             */
            combustivel_id: number;
            /**
             * Tipo
             * @description Tipo da operação: compra ou venda
             * @enum {string}
             */
            tipo: "compra" | "venda";
            /**
             * Data
             * Format: date
             * @description Data da operação
             */
            data: string;
            /**
             * Litros
             * @description Quantidade de litros
             */
            litros: number;
            /**
             * Selic
             * @description Valor do selic aplicado
             */
            selic: number;
        };
        /** OperacaoResponse */
        OperacaoResponse: {
            /** Id */
            id: number;
            /** Combustivel Id */
            combustivel_id: number;
            /** Tipo */
            tipo: string;
            /**
             * Data
             * Format: date
             */
            data: string;
            /** Ref Id */
            ref_id: number;
            /** Litros */
            litros: number;
            /** Valor */
            valor: number;
            /** Selic */
            selic: number;
        };
        /** PrecoCompra */
        PrecoCompra: {
            /** Combustivel Id */
            combustivel_id: number;
            /** Mes */
            mes: number;
            /** Preco */
            preco: number;
            /** Tributo */
            tributo: number;
            /** Id */
            id: number;
        };
        /** PrecoVenda */
        PrecoVenda: {
            /** Combustivel Id */
            combustivel_id: number;
            /** Mes */
            mes: number;
            /** Preco */
            preco: number;
            /** Tributo */
            tributo: number;
            /** Id */
            id: number;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    get_combustiveis_api_v1_combustiveis_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CombustivelSchema"][];
                };
            };
        };
    };
    listar_ref_compra_api_v1_ref_compra_get: {
        parameters: {
            query?: {
                combustivel_id?: number | null;
                mes?: number | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PrecoCompra"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    listar_ref_venda_api_v1_ref_venda_get: {
        parameters: {
            query?: {
                combustivel_id?: number | null;
                mes?: number | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PrecoVenda"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    criar_operacao_endpoint_api_v1_operacoes_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["OperacaoCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OperacaoResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    obter_balanco_api_v1_balanco_get: {
        parameters: {
            query: {
                /** @description Ano para consulta */
                ano: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BalancoConsultaResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
